# Generated by Django 3.0.2 on 2020-02-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_color', models.CharField(blank=True, max_length=20, null=True)),
                ('car_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
